// src/components/BubbleSortTab.vue
<template>
  <div class="bubble-sort-tab">
    <el-form :model="form" label-width="120px" @submit.prevent>
      <el-form-item label="数字数组">
        <el-input
          v-model="form.numbersText"
          placeholder="请输入逗号分隔的数字，如 5,3,8,1,9,2,7"
          style="width: 400px"
        />
      </el-form-item>
      <el-form-item>
        <el-button type="primary" :loading="loading" @click="execute">
          <el-icon><Pointer /></el-icon>
          执行排序
        </el-button>
        <el-button type="success" :icon="Download" @click="doExport" :disabled="!result">
          导出结果
        </el-button>
      </el-form-item>
    </el-form>

    <el-divider />

    <div v-if="result" class="result-area">
      <el-descriptions title="排序结果" :column="1" border>
        <el-descriptions-item label="sortedArray">
          <span class="array-value">{{ result.sortedArray.join(', ') }}</span>
        </el-descriptions-item>
        <el-descriptions-item label="compareCount">{{ result.compareCount }}</el-descriptions-item>
        <el-descriptions-item label="swapCount">{{ result.swapCount }}</el-descriptions-item>
        <el-descriptions-item label="durationMillis">{{ result.durationMillis }} ms</el-descriptions-item>
      </el-descriptions>
    </div>
    <el-empty v-else description="输入数字数组并点击排序按钮" />
  </div>
</template>

<script setup>
import { ref, reactive } from 'vue'
import { Pointer, Download } from '@element-plus/icons-vue'
import { ElMessage } from 'element-plus'
import { bubbleSort } from '../api/algorithm'

const emit = defineEmits(['track', 'export'])

const loading = ref(false)
const result = ref(null)
const form = reactive({
  numbersText: '5,3,8,1,9,2,7'
})

function parseNumbers() {
  const parts = form.numbersText.split(',').map(s => s.trim()).filter(s => s.length > 0)
  return parts.map(s => {
    const n = parseInt(s, 10)
    if (isNaN(n)) {
      throw new Error(`"${s}" 不是有效数字`)
    }
    return n
  })
}

async function execute() {
  let numbers
  try {
    numbers = parseNumbers()
  } catch (e) {
    ElMessage.error(e.message)
    return
  }
  if (numbers.length === 0) {
    ElMessage.warning('请输入至少一个数字')
    return
  }
  if (numbers.length > 1000) {
    ElMessage.warning('数组长度不能超过1000')
    return
  }

  loading.value = true
  try {
    const res = await bubbleSort({ numbers })
    result.value = res.data
    emit('track', { algorithmType: 'BUBBLE_SORT' })
    ElMessage.success('排序成功')
  } catch (e) {
    console.error(e)
  } finally {
    loading.value = false
  }
}

function doExport() {
  emit('export', {
    algorithmType: 'BUBBLE_SORT',
    numbers: form.numbersText
  })
}
</script>

<style scoped>
.result-area {
  margin-top: 20px;
}
.array-value {
  font-family: 'Courier New', monospace;
  word-break: break-all;
}
</style>

// src/components/BubbleSortTab.tsx
import { useState } from "react";
import { Alert, Button, Card, Form, Input } from "antd";
import { sortArray } from "@/api/bubbleSort";

/**
 * Bubble-sort tab.
 * - Form with a single Input for a comma-separated list of numbers.
 * - Parses the input, posts it to the backend, and displays the sorted array.
 * - On error shows an Alert with a retry button (same pattern as HashTab).
 */
export default function BubbleSortTab() {
  const [raw, setRaw] = useState("");
  const [loading, setLoading] = useState(false);
  const [sorted, setSorted] = useState<number[] | null>(null);
  const [error, setError] = useState<string | null>(null);

  const parseNumbers = (text: string): number[] => {
    return text
      .split(",")
      .map((part) => part.trim())
      .filter((part) => part.length > 0)
      .map((part) => {
        const n = Number(part);
        if (!Number.isFinite(n)) {
          throw new Error(`Invalid number: "${part}"`);
        }
        return n;
      });
  };

  const handleSort = async () => {
    setLoading(true);
    setError(null);
    try {
      const array = parseNumbers(raw);
      const data = await sortArray(array);
      setSorted(data.sorted);
    } catch (err) {
      setError(err instanceof Error ? err.message : String(err));
      setSorted(null);
    } finally {
      setLoading(false);
    }
  };

  const handleRetry = () => {
    void handleSort();
  };

  return (
    <Card title="Bubble Sort">
      <Form layout="vertical">
        <Form.Item label="Numbers (comma-separated)">
          <Input
            value={raw}
            onChange={(e) => setRaw(e.target.value)}
            placeholder="e.g. 5, 3, 8, 1, 9, 2"
          />
        </Form.Item>
        <Form.Item>
          <Button type="primary" loading={loading} onClick={handleSort}>
            Sort
          </Button>
        </Form.Item>
      </Form>

      {error && (
        <Alert
          type="error"
          message="Sort failed"
          description={error}
          showIcon
          action={<Button onClick={handleRetry}>Retry</Button>}
        />
      )}

      {sorted && !error && (
        <Alert
          type="success"
          message="Sorted result"
          description={`[${sorted.join(", ")}]`}
          showIcon
        />
      )}
    </Card>
  );
}
