// src/components/charts/CostTrendChart.vue
<script setup lang="ts">
import { ref, watch, onMounted, onBeforeUnmount } from 'vue'
import * as echarts from 'echarts'
import type { TrendPointVO } from '@/types/cost'

const props = defineProps<{
  data: TrendPointVO[]
}>()

const chartRef = ref<HTMLElement>()
let chartInstance: echarts.ECharts | null = null

function getOption(): echarts.EChartsOption {
  return {
    tooltip: {
      trigger: 'axis'
    },
    legend: {
      data: ['人力成本', '项目成本', '总成本']
    },
    grid: {
      left: '3%',
      right: '4%',
      bottom: '3%',
      containLabel: true
    },
    xAxis: {
      type: 'category',
      boundaryGap: false,
      data: props.data.map((d) => d.period)
    },
    yAxis: {
      type: 'value'
    },
    series: [
      {
        name: '人力成本',
        type: 'line',
        data: props.data.map((d) => d.humanCost)
      },
      {
        name: '项目成本',
        type: 'line',
        data: props.data.map((d) => d.projectCost)
      },
      {
        name: '总成本',
        type: 'line',
        data: props.data.map((d) => d.totalCost)
      }
    ]
  }
}

function renderChart() {
  if (!chartRef.value) return
  if (!chartInstance) {
    chartInstance = echarts.init(chartRef.value)
  }
  chartInstance.setOption(getOption())
}

onMounted(() => {
  renderChart()
})

watch(
  () => props.data,
  () => {
    renderChart()
  },
  { deep: true }
)

onBeforeUnmount(() => {
  if (chartInstance) {
    chartInstance.dispose()
    chartInstance = null
  }
})
</script>

<template>
  <div ref="chartRef" class="cost-trend-chart" />
</template>

<style scoped>
.cost-trend-chart {
  width: 100%;
  height: 350px;
}
</style>

// src/components/CostTrendChart.tsx
import ReactECharts from 'echarts-for-react'
import type { DimensionStat } from '../types/cost'

interface Props {
  data: DimensionStat[]
  loading?: boolean
}

export default function CostTrendChart({ data, loading }: Props) {
  const option = {
    title: { text: '月度成本趋势', left: 'center' },
    tooltip: { trigger: 'axis' },
    xAxis: { type: 'category', data: data.map((d) => d.dimensionName) },
    yAxis: { type: 'value', name: '金额 (¥)' },
    series: [
      {
        name: '成本',
        type: 'line',
        smooth: true,
        data: data.map((d) => d.amount),
        areaStyle: { opacity: 0.3 },
      },
    ],
    grid: { left: '8%', right: '5%', bottom: '10%' },
  }
  return <ReactECharts option={option} style={{ height: 350 }} showLoading={loading} />
}
